In [1]:
import numpy as np

In [3]:
#Ejercicio 1: sumar dos matrices y obtener los resultados
matriz1=np.array([[1,2],[10,30]])
matriz2=np.array([[34,55],[56,70]])
resultado=matriz1+matriz2
print("La matriz 1 es: ")
print(matriz1)
print("La matriz 2 es: ")
print(matriz2)
print("El resultado de sumar las dos matrices es: ")
print(resultado)

La matriz 1 es: 
[[ 1  2]
 [10 30]]
La matriz 2 es: 
[[34 55]
 [56 70]]
El resultado de sumar las dos matrices es: 
[[ 35  57]
 [ 66 100]]


In [4]:
#Un array con valor espaciados
arreglo=np.linspace(0,9,10)
print("Arreglo")
print(arreglo)

Arreglo
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
#Operaciones
arreglo=np.array([3,6,55,12])
media=np.mean(arreglo)
suma=np.sum(arreglo)
maximo=np.max(arreglo)
minimo=np.min(arreglo)
print("Media:",media, "Suma:",suma, "Maximo:",maximo, "Minimo:",minimo )

Media: 19.0 Suma: 76 Maximo: 55 Minimo: 3


In [16]:
datosAleatorios=np.random.rand(1000)
print("Primeros 10: ", datosAleatorios[:10])

Primeros 10:  [0.35923732 0.77395463 0.31036915 0.17600553 0.81982417 0.74745746
 0.17209122 0.03660317 0.62203549 0.84160307]


In [17]:
datos=np.array([22,18,25,30,28,24,20,19,27])
media=np.mean(datos)
mediana=np.median(datos)
desviacionEstandar=np.std(datos)
print("Media:",media, "Mediana:",mediana, "Desviación estandar:",desviacionEstandar)


Media: 23.666666666666668 Mediana: 24.0 Desviación estandar: 3.972125095937662


In [20]:
datos=np.array([12,8,15,10,6,18,7,14,9,11])
umbral=10
datosMayoresA10=datos[datos>umbral]
print("Los datos mayores a",umbral," son los siguientes: ")
print(datosMayoresA10)

Los datos mayores a 10  son los siguientes: 
[12 15 18 14 11]


In [21]:
matriz=np.array([[3,4,5],[89,90,85],[23,45,78]])
matrizTranspuesta=matriz.T
matrizProducto=np.dot(matriz,matriz)
print("Matriz original: ")
print(matriz)
print("Matriz transpuesta: ")
print(matrizTranspuesta)
print("Producto de matrices: ")
print(matrizProducto)


Matriz original: 
[[ 3  4  5]
 [89 90 85]
 [23 45 78]]
Matriz transpuesta: 
[[ 3 89 23]
 [ 4 90 45]
 [ 5 85 78]]
Producto de matrices: 
[[  480   597   745]
 [10232 12281 14725]
 [ 5868  7652 10024]]


In [26]:
arreglo=np.arange(10)
matrizResaped=arreglo.reshape(2,5)
matriz=np.array([[11,12,13,14,15],[16,17,18,19,20]])
matrizConcat=np.concatenate((matrizResaped,matriz),axis=0) #con axis=0 seleccionamos el largo de la columna

print("Arreglo: ")
print(arreglo)
print("Matriz Resaped")
print(matrizResaped)
print("Matriz concatenada: ")
print(matrizConcat)

Arreglo: 
[0 1 2 3 4 5 6 7 8 9]
Matriz Resaped
[[0 1 2 3 4]
 [5 6 7 8 9]]
Matriz concatenada: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [11 12 13 14 15]
 [16 17 18 19 20]]
