In [1]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/93/fd/3f826c6d15d3bdcf65b8031e4835c52b7d9c45add25efa2314b53850e1a2/numpy-1.26.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.1 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.1 kB ? eta -:--:--
     ------------------------------- ------ 51.2/61.1 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.1/61.1 kB 540.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 2.6 MB/s eta 0:00:06
    --------------------------------------- 0.2/15.8 MB 2.9 MB/s eta 0:00:06
   - -------------------------------------- 0.5/15.8 MB 3.5 MB/s eta 0:00:05
   - -------------------------------------- 0.7/15.8 MB 4.5 MB/s eta 0:00:04
   -- ------------------------------------- 1.2/15.8 MB 5.7 MB/s eta 0:00:03
   --- ----------------------------

In [2]:
import numpy as np

In [7]:
#listas
lista=[1,2,3,4,5,6]
array=np.array(lista)
print(lista)
print(type(array))
print(array)

[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [9]:
lista2=[[1,2,3],[2,5,6],[3,5,6]]
array2=np.array(lista2)
print(array2)

[[1 2 3]
 [2 5 6]
 [3 5 6]]


In [12]:
#Rango de una array especificando el número
array3=np.arange(6)
print(array3)
array4=np.arange(2,15,2) #inicio, al número que va, incremento
print(array4)

[0 1 2 3 4 5]
[ 2  4  6  8 10 12 14]


In [14]:
#matriz de ceros
matriz0=np.zeros((4,5))
print(matriz0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#matriz de unos
matriz1=np.ones((4,5))
print(matriz1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#matriz indentidad
metrizIdentidad=np.eye(7)
print(metrizIdentidad)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [20]:
matrizAletoria=np.random.randint(1,51,20)
print(matrizAletoria)

[18 43 19  5 12 22 18  3 19 20 41  8  6 26 39 22 32 35  6 41]


In [21]:
array=np.random.randint(1,201,30)
print(array)

[180  88 110  59 176 193  64  36 175 182  16  23 183  43 134 178  79 120
  96 200  91  12 118 180 189  94  40  14 103  86]


In [22]:
matriz=array.reshape(5,6)
print(matriz)

[[180  88 110  59 176 193]
 [ 64  36 175 182  16  23]
 [183  43 134 178  79 120]
 [ 96 200  91  12 118 180]
 [189  94  40  14 103  86]]


In [27]:
array=np.random.randint(1,901,200)
print(array)
maximo=array.max()
print("El valor maximo es: "+ maximo)

[311 328 828 113 273 664 671 583 549 879 688 827 591 739  77 574 479 206
 430 708 589 773 519 832 156 246 451 528 410 494 159 206 381 297 819 891
 103 794 305 828 274 434 523 588 853 306 128 837 438 413 476 746  17 846
 832 522 515 794 694 624  90 618 335 429 868 202 138 456  16 826 200 147
 389 386 766 650 579 410  48 484 501 225 456 753 838 481 598 381 340 498
  17 826 196 828 289 743  68 157 463 107 880  58 520 705 188 543 241  67
 596 159 369 336 355 115  43 302 630 618 261 786 888 857 576 309 771 347
 548 544 519  69 835 237 322 408  45 174  99 435  42 766  66 251 107 360
 445 627 541 615 386 823  62 354   4 577 502  24 768 546 734 789 636 636
 463  64  70 467 528 651 741 459 365 812  90 187  56  49 160 170 856 564
 387 348 122 460 899 125 278 155 249 463 695 262 699 499 183 890 256 299
 610 257]


TypeError: can only concatenate str (not "builtin_function_or_method") to str