In [1]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/93/fd/3f826c6d15d3bdcf65b8031e4835c52b7d9c45add25efa2314b53850e1a2/numpy-1.26.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.1 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.1 kB ? eta -:--:--
     ------------------------------- ------ 51.2/61.1 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.1/61.1 kB 540.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 2.6 MB/s eta 0:00:06
    --------------------------------------- 0.2/15.8 MB 2.9 MB/s eta 0:00:06
   - -------------------------------------- 0.5/15.8 MB 3.5 MB/s eta 0:00:05
   - -------------------------------------- 0.7/15.8 MB 4.5 MB/s eta 0:00:04
   -- ------------------------------------- 1.2/15.8 MB 5.7 MB/s eta 0:00:03
   --- ----------------------------

In [2]:
import numpy as np

In [7]:
#listas
lista=[1,2,3,4,5,6]
array=np.array(lista)
print(lista)
print(type(array))
print(array)

[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [9]:
lista2=[[1,2,3],[2,5,6],[3,5,6]]
array2=np.array(lista2)
print(array2)

[[1 2 3]
 [2 5 6]
 [3 5 6]]


In [12]:
#Rango de una array especificando el número
array3=np.arange(6)
print(array3)
array4=np.arange(2,15,2) #inicio, al número que va, incremento
print(array4)

[0 1 2 3 4 5]
[ 2  4  6  8 10 12 14]


In [14]:
#matriz de ceros
matriz0=np.zeros((4,5))
print(matriz0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#matriz de unos
matriz1=np.ones((4,5))
print(matriz1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#matriz indentidad
metrizIdentidad=np.eye(7)
print(metrizIdentidad)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [20]:
matrizAletoria=np.random.randint(1,51,20)
print(matrizAletoria)

[18 43 19  5 12 22 18  3 19 20 41  8  6 26 39 22 32 35  6 41]


In [21]:
array=np.random.randint(1,201,30)
print(array)

[180  88 110  59 176 193  64  36 175 182  16  23 183  43 134 178  79 120
  96 200  91  12 118 180 189  94  40  14 103  86]


In [22]:
matriz=array.reshape(5,6)
print(matriz)

[[180  88 110  59 176 193]
 [ 64  36 175 182  16  23]
 [183  43 134 178  79 120]
 [ 96 200  91  12 118 180]
 [189  94  40  14 103  86]]


In [30]:
array=np.random.randint(1,901,200)
print(array)
maximo=array.max()
minimo=array.min()
print("El valor maximo es: ", maximo)
print("El valor minimo es: ", minimo)


[811 845  11 162 839 710 147 348 128 763 781 386 254 773 750 898 679 851
 437 463 402 866 329 600 556 168 359 868  74  68  84 636 359   7 734 744
  43 237 876  22 430 521 489 248 510 750 347 605 150 536 264 546 560 671
 318 841 180 668 666 380 124 171 594 491 585 449 290 420 502 853 543 180
 300 605 302 828 463 327 667 570  80 385 200 228 842 686 558 837 806 615
 829  91 851 188 663 767  68 699 535 672 290 493 413 140 541 575 140 251
 670  32 638  84 434 844 692 811 134 674 341 242   7  50 313 263 439 224
  46 158 608 428 524 686 380 687 424 867 654 752 785 408 326 279 366 737
 296 726 436 313  35 282 338 539 303 102 357 523 727 198 593  84 702 401
  41  59 866 171 507 731 124 635 529 633 576 210   3 894  46 317 478 360
  71 710 574 760 735 658 197 654 238 726 898 360 328 581 506   4 711 325
 501 333]
El valor maximo es:  898
El valor minimo es:  3


In [45]:
array=np.arange(1,11)
print(array)
print(array[2])
print(array[5:])
print(array[:6])

[ 1  2  3  4  5  6  7  8  9 10]
3
[ 6  7  8  9 10]
[1 2 3 4 5 6]


In [49]:
array2=array.copy()
print(array)
print(array2)
array[4]=2000
print(array)



[   1    2    3    4 1000    6    7    8    9   10]
[   1    2    3    4 1000    6    7    8    9   10]
[   1    2    3    4 2000    6    7    8    9   10]


In [52]:
print(matriz)

[[180  88 110  59 176 193]
 [ 64  36 175 182  16  23]
 [183  43 134 178  79 120]
 [ 96 200  91  12 118 180]
 [189  94  40  14 103  86]]


In [55]:
print(matriz[0])
print(matriz[:2])
print(matriz[1][2])

[180  88 110  59 176 193]
[[180  88 110  59 176 193]
 [ 64  36 175 182  16  23]]
175


In [57]:
print(matriz[:,:1])

[[180]
 [ 64]
 [183]
 [ 96]
 [189]]


In [59]:
#operaciones con matrices
print(matriz)
print("-----------------------------")
print(matriz+10)

[[180  88 110  59 176 193]
 [ 64  36 175 182  16  23]
 [183  43 134 178  79 120]
 [ 96 200  91  12 118 180]
 [189  94  40  14 103  86]]
-----------------------------
[[190  98 120  69 186 203]
 [ 74  46 185 192  26  33]
 [193  53 144 188  89 130]
 [106 210 101  22 128 190]
 [199 104  50  24 113  96]]


In [60]:
print(matriz+matriz)

[[360 176 220 118 352 386]
 [128  72 350 364  32  46]
 [366  86 268 356 158 240]
 [192 400 182  24 236 360]
 [378 188  80  28 206 172]]


In [61]:
print(matriz*10)

[[1800  880 1100  590 1760 1930]
 [ 640  360 1750 1820  160  230]
 [1830  430 1340 1780  790 1200]
 [ 960 2000  910  120 1180 1800]
 [1890  940  400  140 1030  860]]


In [63]:
print(np.max(matriz))

200


In [65]:
#condiciones
condiciones=matriz>100
print(condiciones)

[[ True False  True False  True  True]
 [False False  True  True False False]
 [ True False  True  True False  True]
 [False  True False False  True  True]
 [ True False False False  True False]]


In [67]:
condiciones=(matriz%2!=0)
print(condiciones)
#print(matriz[condiciones])

[[False False False  True False  True]
 [False False  True False False  True]
 [ True  True False False  True False]
 [False False  True False False False]
 [ True False False False  True False]]


In [69]:
lista=np.arange(5,41)
print(lista)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40]


In [70]:
lista=lista.reshape(3,12)
print(lista)

[[ 5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36 37 38 39 40]]


In [71]:
print(lista[2,4])

33


In [72]:
arrayPrimitiva=np.random.randint(1,50,6) # va de 1 al 49 (1,50) y elegi 6 numeros
print("La combinación ganadora es: ", arrayPrimitiva)

La combinación ganadora es:  [26 13 11 25 19 46]
